name: Release app
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Run this job on the following operating systems
    strategy:
      matrix:
        os:
          [
            { name: "linux", image: "ubuntu-latest" },
            { name: "windows", image: "windows-latest" },
            { name: "macos", image: "macos-latest" },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Use Node.js and install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Build Vue front end
        run: npm run build

      - name: Build Electron app
        run: npm run make

      - name: Publish app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
